### ISSUE TITLE
Packaging license file

### ISSUE THREAD

**Issue by jakirkham** [elijahr/python-autopxd2#26]
Would be good if [the `license_files`]( https://wheel.readthedocs.io/en/stable/user_guide.html#including-license-files-in-the-generated-wheel-file ) were added to the [setup.cfg]( https://github.com/pypa/sampleproject/blob/90d44abe361688aba5a189e661423863b34f5208/setup.cfg#L1-L4 ) to ensure there are packaged in `sdist`s, `whl`s, etc. and installed alongside the code.

https://github.com/gabrieldemarmiesse/python-autopxd2/blob/e175c42e39b7a81317de033fe910ab53959ccd8c/setup.cfg#L1-L2

**Comment by jakirkham** [comment]
This could also be added in `setup.py` if preferred

**Comment by elijahr** [comment]
@jakirkham this has been released in v2.0.2.

**Comment by jakirkham** [comment]
Great thank you! 😄
