### ISSUE TITLE
Adding `python_requires`

### ISSUE THREAD

**Issue by jakirkham** [elijahr/python-autopxd2#31]
To make it clearer the intended Python versions supported (and protect users against installing packages incompatible with their Python version), it would be good to add [`python_requires`]( https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires ) like in [this example]( https://github.com/pypa/sampleproject/blob/90d44abe361688aba5a189e661423863b34f5208/setup.py#L134-L138 )

**Comment by elijahr** [comment]
@jakirkham this has been released in v2.0.2.

**Comment by jakirkham** [comment]
Awesome thank you! 😄
