### ISSUE TITLE
`importlib_resources` requirement?

### ISSUE THREAD

**Issue by jakirkham** [elijahr/python-autopxd2#33]
Looks like the `importlib_resources` requirement was added recently. IIUC this is a backport package from Python 3.7 to earlier Python versions. However the environment marker here suggests it applies to Python 3.6+. Is this needed for later Python versions for some reason?

https://github.com/gabrieldemarmiesse/python-autopxd2/blob/d0506592f6076d7a87ef19cd7441197a749410a3/setup.cfg#L28

**Comment by elijahr** [comment]
@jakirkham there was no particular reason this was included, and I think it can be removed. I've opened #34 - does that looks right to you?

**Comment by jakirkham** [comment]
Thanks for following up @elijahr! 😀

Oh ok. If it is not needed, agree dropping makes sense 🙂

**Comment by elijahr** [comment]
@jakirkham this has been released in v2.0.3

**Comment by jakirkham** [comment]
Thank you! 😀
