### ISSUE TITLE
Fails on `#include <string>`

### ISSUE THREAD

**Issue by djacobs010** [elijahr/python-autopxd2#35]
How do I avoid failing on `#include <string>`?
```
<stdin>:1:10: fatal error: string: No such file or directory
```

Do I have to add preprocessor to my path or something?

**Comment by elijahr** [comment]
@danielcjacobs is `#include <string>` a C++-ism? I think this project only works with C code.

**Comment by djacobs010** [comment]
Oh yes, you're right, thanks
