### ISSUE TITLE
Transfer ownership

### ISSUE THREAD

**Issue by elijahr** [elijahr/python-autopxd2#41]
Hello @gabrieldemarmiesse,
If you are open to it, would you please [transfer this repository](
https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository) to me?
I want to automate releases and need to be able to update secrets to do that.

**Comment by gabrieldemarmiesse** [comment]
Hello @elijahr! Sure thing! Do you know if there is any way to redirect links automatically? That would help

**Comment by elijahr** [comment]
@gabrieldemarmiesse yes, I believe that after the transfer, any request to github.com/gabrieldemarmiesse/python-autopxd2 will be redirected to github.com/elijahr/python-autopxd2

From [the docs](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#whats-transferred-with-a-repository):

> All links to the previous repository location are automatically redirected to the new location. When you use git clone, git fetch, or git push on a transferred repository, these commands will redirect to the new repository location or URL. 

I'll also update URLs in the source, and issue a new release to pypi with the updated URLs.

**Comment by gabrieldemarmiesse** [comment]
Very cool. I'll transfer it now then

**Comment by elijahr** [comment]
I have not gotten an email or github notification yet - does it say the transfer has been initiated? 
The documentation is unclear on how GitHub would notify me or how to accept it.

**Comment by gabrieldemarmiesse** [comment]
Sorry, I had something that came up at work. You should have recieved an email now

**Comment by elijahr** [comment]
Got it. Thank you! Says it is transferring now.

**Comment by gabrieldemarmiesse** [comment]
it seems that worked :)

**Comment by chrisjbillington** [comment]
That even worked to pull in me to be subscribed here, since I was subscribed to the original repository. Cool to know!

**Comment by elijahr** [comment]
@gabrieldemarmiesse two more things:
Can you change me to the owner on pypi? https://pypi.org/manage/project/autopxd2/collaboration/
Can you change me to the owner on test.pypi? https://test.pypi.org/manage/project/autopxd2/collaboration/
